# -*- coding: utf-8 -*-
"""

template strings for various structure file types


Created on Mon Apr  1 11:32:36 2019

@author: pce
"""
# METHOD NAME SG lpa lpb lpc lpal lpbe lpga SITE_BLOCK
template_str = """
str
    ' generated by {METHOD}
    phase_name "{NAME}"
    scale @ 1e-04
    space_group "{SG}"
    a {lpa}
    b {lpb}
    c {lpc}
    al {lpal}
    be {lpbe}
    ga {lpga}
    
    load site x y z occ beq {{
        {SITE_BLOCK}
    
    }}

"""

# NAME, METHOD, lpa, lpb, lpc, lpal, lpbe, lpga, SG, SITE_BLOCK
template_cif = """
data_{NAME}
_audit_creation_method  "generated by {METHOD}"

_cell_length_a  {lpa}
_cell_length_b  {lpb}
_cell_length_c  {lpc}
_cell_angle_alpha  {lpal}
_cell_angle_beta   {lpbe}
_cell_angle_gamma  {lpga}

_symmetry_space_group_name_h-m  {SG}

loop_
_atom_site_label
_atom_site_type_symbol
_atom_site_occupancy
_atom_site_fract_x
_atom_site_fract_y
_atom_site_fract_z
_atom_site_B_iso_or_equiv
{SITE_BLOCK}

"""


# METHOD, DATA, STR, NAME
template_inp = """
/*

generated by {METHOD}

*/

include anisocs.inc

'----------------------------------------------- refinement keys ---------
do_errors
no_LIMIT_warnings
r_wp 1
r_

'-------------------------------------------------global parameters-------
prm csl 1000 min 1 max 100000

'-------------------------------------------------- data -----------------
xdd "{DATA}"
	x_calculation_step 0.005
    bkg @  1067.80394  23611.8101 -28917.2134  19778.5947 -7883.4983 -289.693677
	start_X 1.
	finish_X 20
	LP_Factor( 90 )
	One_on_X(@, 178068)
	Zero_Error( @ ,-0.00307`_0.00080)
	Rp 5000
	Rs 1000
	Simple_Axial_Model( , 0.01)
	lam
		ymin_on_ymax  0.001
		la  1 lo  0.2114 lh  0.0001
	
	' instert test structure here ------------------------------'
    {STR}


      
      ' microstructure models ----------------------------------'
      CS_L(csl) :  1
      
      #ifdef USEPO
         PO_Spherical_Harmonics(sh, 8) 

      #endif

      #ifdef USEANISOCS
         AnisoCS(2,       ' elliptic cylinder
                 0, 0, 1, ' z-axis vector
                 1, 0, 0, ' x-axis vector
                 @, 20, @, 20, @, 5,  'spatial extent in *a* *b* *c*
                 !pc, 0, !tc, 0, !nc, 0,
                 0
                 )
      #endif
      
      Out_CIF_STR(generated_{NAME}.cif)

    Out_Yobs_Ycalc_and_Difference({NAME}_Yobs_Ycalc_and_Difference.txt)
"""
